# Generated by Django 6.0.3 on 2026-03-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('tipo', models.CharField(choices=[('CUIDADOR', 'Cuidador/a'), ('PACIENTE', 'Paciente/Adulto Mayor')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('monto_pago', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuidador', models.ForeignKey(limit_choices_to={'tipo': 'CUIDADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_prestados', to='appointments.persona')),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo': 'PACIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_recibidos', to='appointments.persona')),
            ],
        ),
    ]
