# Generated by Django 6.0.3 on 2026-03-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Mi Negocio', max_length=100)),
                ('pedir_email', models.BooleanField(default=True)),
                ('pedir_telefono', models.BooleanField(default=True)),
                ('pedir_direccion', models.BooleanField(default=False)),
                ('pedir_fecha_nacimiento', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='observaciones',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='cuidador',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='monto_pago',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='paciente',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(default=60, help_text='Duración en minutos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default='Servicio General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('PACIENTE', 'Paciente'), ('CUIDADOR', 'Cuidador'), ('CLIENTE', 'Cliente General')], default='PACIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cuidador', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'CUIDADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_cuidador', to='appointments.persona')),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo': 'PACIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_paciente', to='appointments.persona')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.servicio')),
            ],
        ),
    ]
