# Generated by Django 6.0.3 on 2026-03-10 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_configuracionsistema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora',
        ),
        migrations.AddField(
            model_name='turno',
            name='color_etiqueta',
            field=models.CharField(default='#3788d8', help_text='Color Hex (ej: #3788d8)', max_length=7),
        ),
        migrations.AddField(
            model_name='turno',
            name='fin',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de término (calculada o manual)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='titulo',
            field=models.CharField(default='Cita General', help_text='Ej: Control Mensual - Juan', max_length=200),
            preserve_default=False,
        ),
    ]
