# Generated by Django 6.0.3 on 2026-03-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_turno_fecha_remove_turno_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='notas',
        ),
        migrations.AddField(
            model_name='persona',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico Principal'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tratamiento_vigente',
            field=models.TextField(blank=True, null=True, verbose_name='Tratamientos Activos'),
        ),
        migrations.AddField(
            model_name='turno',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Evolución clínica o notas de la visita', null=True),
        ),
    ]
