# Generated by Django 6.0.3 on 2026-03-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_turno_notas_persona_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='nombre_negocio',
            field=models.CharField(default='Vivand - Gestión de Cuidados', max_length=100),
        ),
        migrations.AlterField(
            model_name='turno',
            name='color_etiqueta',
            field=models.CharField(default='#3788d8', help_text='Color Hex', max_length=7),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fin',
            field=models.DateTimeField(help_text='Fecha y hora de término'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Evolución clínica o notas de la visita escribas por el cuidador', null=True),
        ),
    ]
